name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        host: windows
        target: desktop
        arch: win64_msvc2019_64

    - name: Download Spectral
      run: git clone --recursive https://gitlab.com/b0/spectral
      
    - name: Install dependencies
      working-directory: ./spectral
      run: |
        git clone https://gitlab.matrix.org/matrix-org/olm.git
        cd olm
        cmake -LA -G "NMake Makefiles JOM" -H. -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="install" -DBUILD_SHARED_LIBS=NO
        cmake --build build --target install
        cd ..
        git clone https://github.com/frankosterfeld/qtkeychain.git
        cd qtkeychain
        cmake -LA -G "NMake Makefiles JOM" -H. -Bbuild -DCMAKE_CXX_FLAGS="/EHsc /W3" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="install" -DQTKEYCHAIN_STATIC=ON
        cmake --build build --target install
        cd ..
        git clone https://github.com/commonmark/cmark.git
        cd cmark
        cmake -LA -G "NMake Makefiles JOM" -H. -Bbuild -DCMAKE_CXX_FLAGS="/EHsc /W3" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="install" -DCMARK_SHARED=ON -DCMARK_STATIC=OFF -DCMARK_TESTS=OFF
        cmake --build build --target install
        cd ..
    - name: Build
      working-directory: ./spectral
      run: |
        cmake -LA -G "NMake Makefiles JOM" -H. -Bbuild -DCMAKE_CXX_FLAGS="/EHsc /W3" -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_INSTALL_PREFIX="install" -DUSE_INTREE_LIBQMC=1 -DQt5Keychain_DIR="qtkeychain/install/lib/cmake/Qt5Keychain" -DOlm_DIR=olm/install/lib/cmake/Olm -DCMARK_LIBRARY=./cmark/install/lib/cmark.lib -DCMARK_INCLUDE_DIR=./cmark/install/include -DDEPLOY_VERBOSITY=%DEPLOY_VERBOSITY%
        cmake --build build
        
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: All
        path: ./spectral
